### ISSUE TITLE
Scan Now button is disabled

### ISSUE THREAD

**Issue by kitsos** [thanhtri/plagiarism_programming#2]
I am using Moodle 2.3.4 and although all the setups are correct according to the Installation and setup guid The scan Now button is disabled and above of that button it says"JPlag: not started
The next scanning is scheduled on Thu 14 Feb
If you want to trigger the scanning immediately (in case of late submissions, extension...), please click the button below! (note that it doesn't affect the scheduled scanning)
Not enough submissions to scan!" . Any help in what am I doing wrong? Thank you in advance.
![programming_jplag](https://f.cloud.github.com/assets/2872715/155388/9f144a6c-7645-11e2-8013-59a51da4e254.jpg)

**Comment by thanhtri** [comment]
Hi,

I think you had everything right.
The "Not enough submission to scan" message only appears when you have less than 2 submissions.
However, I see the message 'View 2 submitted assignments' on the bread-cum. Therefore, it should be enough submissions to scan.

Could you check that these 2 submissions are uploaded properly (that you could download them again), and if yes, could you upload one more assignment?

Looking forward to your update! Thank you!

PS: it is a little weird that Moodle 2.3 has the bread-cum like this. It looks like more Moodle 2.2 than 2.3. It's not important, anyway :)

**Comment by kitsos** [comment]
I am getting exactly the same message and "Scan Now" button is disabled. They are uploaded properly. I have added a third one and still the same message. It is 2.3.4+ . Any idea in what point am I wrong It could help.

**Comment by thanhtri** [comment]
Hi! This may be a quite major bug. The latest Moodle version I tested on is 2.3.2.
I will test with 2.3.4 and get back to you soon.
By the way, which programming language you use for the assignment?

**Comment by kitsos** [comment]
I tested with java. I will also want to use c++. Thank you very much for your answer.

**Comment by thanhtri** [comment]
Hi!
I had a go with Moodle 2.3.4 and everything is fine. Just like the 2.3.2.
I wonder if you logged in as each student and submit on their behalf. If yes, that should work right.

You could have a look at my Moodle test instance:
http://moodletest.lnthanhtri.com/mod/assign/view.php?id=5&action=grading
or
http://moodletest.lnthanhtri.com/mod/assign/view.php?id=2&action=grading
It runs 2.3.4. Login user is aash6, password is MoodleTest1#

I am very curious at the problem you encounter.
If it is accessible and just a test instance, could you grant me access to it to see what's happening?

**Comment by kitsos** [comment]
could you provide me a mail of yours cause I think is not wise to share test accounts in public.

**Comment by kitsos** [comment]
what kind of assignment do you use cause i am using assignment 2.2 -> Advance uploading files and online judge. May is that the reason for being disabled?? Although at the setup of the assignment it works fine. I can use yours plugin setups.

**Comment by thanhtri** [comment]
Ah!! I understand the reason. It is because you use the assignment 2.2 in Moodle 2.3.
Currently, it's not possible to use the old assignment module with the new Moodle since the API calling to plagiarism plugin doesn't permit that (the same API call for 2 different assignment modules and the plugin don't know what module name exactly; so it has to assume the new assignment in 2.3 and the old one in 2.0 -> 2.2).

Initially I left it with the old assignment but some complain they couldn't use in 2.3, and the old module exists in 2.3 for transition purpose only, it makes more sense to switch to the new assignment module.

Please upgrade your assignment data in 2.3.
Or let me see if there is a way to accommodate both the old and new assignment module within the new Moodle.

**Comment by kitsos** [comment]
If i will use moodle 2.2 i will not have such problem? I am asking that because other plugins i use cannot be upgraded to  2.3 version. Thank you for your support and for making me understand the exact problem. "Upload files" can be upgraded and works fine. If you find solution to make it work with both i would be really appreciate. In fact i am already appreciate for all the help you provide to me and for your time.

**Comment by kitsos** [comment]
"I am asking that because other plugins i use cannot be upgraded to 2.3 version." I mean that need assignment 2.2 type to work.

**Comment by thanhtri** [comment]
Yes, you could use Moodle 2.2 and it should work smoothly.
I will give you an update to the plugin that would work with assignment 2.2 in Moodle 2.3 today or tomorrow.
However, it will place an overhead on the maintenance and further upgrading. I think you shouldn't plan to stay in this incompatibility for so long.

**Comment by thanhtri** [comment]
Hi,

I have made a small update to the plugin and it is now backward compatible with assignment module 2.2 in Moodle 2.3.
You could download it here in Github, not in Moodle plugin repository (I haven't released there yet before doing more testing on this amendment).

If you have other errors, please inform me. Getting this to work smoothly is very important for me.
Thanks,

**Comment by thanhtri** [comment]
I suppose that your problem was resolved!
I will close this issue for now.

**Comment by kitsos** [comment]
yes and i really appreciate your support
